from dash import dcc

study_year = [
    {"label": "2019", "value": "p00004"},
    {"label": "2020", "value": "p00010"},
    {"label": "2021", "value": "p00020"},
    {"label": "2022", "value": "p00061"},
]

parameters = {
    "p00004": "Stream width, feet",
    "p00010": "Temperature, water, degrees Celsius",
    "p00020": "Temperature, air, degrees Celsius",
    "p00061": "Discharge, instantaneous, cubic feet per second",
    "p00063": "Number of sampling points, count",
    "p00095": "Specific conductance, water, unfiltered, microsiemens per centimeter at 25 degrees Celsius",
    "p00191": "Hydrogen ion, water, unfiltered, calculated, milligrams per liter",
    "p00400": "pH, water, unfiltered, field, standard units",
    "p00403": "pH, water, unfiltered, laboratory, standard units",
    "p00405": "Carbon dioxide, water, unfiltered, milligrams per liter",
    "p00681": "Organic carbon, water, filtered, milligrams per liter",
    "p00900": "Hardness, water, milligrams per liter as calcium carbonate",
    "p00905": "Noncarbonate hardness, water, filtered, lab, milligrams per liter as calcium carbonate",
    "p00915": "Calcium, water, filtered, milligrams per liter",
    "p00925": "Magnesium, water, filtered, milligrams per liter",
    "p00930": "Sodium, water, filtered, milligrams per liter",
    "p00931": "Sodium adsorption ratio (SAR), water, number",
    "p00932": "Sodium fraction of cations, water, percent in equivalents of major cations",
    "p00935": "Potassium, water, filtered, milligrams per liter",
    "p00940": "Chloride, water, filtered, milligrams per liter",
    "p00945": "Sulfate, water, filtered, milligrams per liter",
    "p00950": "Fluoride, water, filtered, milligrams per liter",
    "p00955": "Silica, water, filtered, milligrams per liter as SiO2",
    "p01000": "Arsenic, water, filtered, micrograms per liter",
    "p01002": "Arsenic, water, unfiltered, micrograms per liter",
    "p01025": "Cadmium, water, filtered, micrograms per liter",
    "p01027": "Cadmium, water, unfiltered, micrograms per liter",
    "p01040": "Copper, water, filtered, micrograms per liter",
    "p01042": "Copper, water, unfiltered, recoverable, micrograms per liter",
    "p01045": "Iron, water, unfiltered, recoverable, micrograms per liter",
    "p01046": "Iron, water, filtered, micrograms per liter",
    "p01049": "Lead, water, filtered, micrograms per liter",
    "p01051": "Lead, water, unfiltered, recoverable, micrograms per liter",
    "p01055": "Manganese, water, unfiltered, recoverable, micrograms per liter",
    "p01056": "Manganese, water, filtered, micrograms per liter",
    "p01090": "Zinc, water, filtered, micrograms per liter",
    "p01092": "Zinc, water, unfiltered, recoverable, micrograms per liter",
    "p29801": "Alkalinity, water, filtered, fixed endpoint (pH 4.5) titration, laboratory, milligrams per liter as calcium carbonate",
    "p30209": "Discharge, instantaneous, cubic meters per second",
    "p50015": "Transit rate, sampler, feet per second",
    "p50280": "Site visit purpose, code",
    "p63676": "Turbidity, water, unfiltered, broad band light source (400-680 nm), detectors at multiple angles including 90 +-30 degrees, ratiometric correction, NTRU",
    "p70301": "Dissolved solids, water, filtered, sum of constituents, milligrams per liter",
    "p70302": "Dissolved solids, water, short tons per day",
    "p70303": "Dissolved solids, water, filtered, short tons per acre-foot",
    "p70331": "Suspended sediment, sieve diameter, percent smaller than 0.0625 millimeters",
    "p72219": "Sampler nozzle material, code",
    "p72220": "Sampler nozzle diameter, code",
    "p80154": "Suspended sediment concentration, milligrams per liter",
    "p80155": "Suspended sediment discharge, short tons per day",
    "p82398": "Sampling method, code",
    "p84164": "Sampler type, code",
    "p84171": "Sample splitter type, field, code",
    "p84182": "Bottle or bag sampler material (construction), code",
    "p90095": "Specific conductance, water, unfiltered, laboratory, microsiemens per centimeter at 25 degrees Celsius",
    "p91157": "Suspended sediment, sediment mass recovered from whole water sample, dry weight, grams",
    "p91165": "Suspended sediment, between 0.063 and 4 mm sieve diameter, sediment mass analyzed for particle size fractions, dry weight, grams",
    "p99105": "Type of replicate, code",
    "p99111": "Type of quality assurance data associated with sample, code",
    "p99156": "Sulfuric acid NWIS lot number, 4.5 N (1:7), 1 mL, National Field Supply Service (NFSS) stock number Q438FLD",
    "p99159": "Nitric acid NWIS lot number, 7.5-7.7 N, 2 mL, National Field Supply Service (NFSS) stock number Q436FLD",
    "p99161": "Conductance standard NWIS lot number, 100 uS/cm KCl, National Field Supply Service (NFSS) stock number Q43FLD",
    "p99163": "Conductance standard NWIS lot number, 500 uS/cm KCl, National Field Supply Service (NFSS) stock number Q45FLD",
    "p99164": "Conductance standard NWIS lot number, 750 uS/cm KCl, National Field Supply Service (NFSS) stock number Q46FLD",
    "p99171": "pH 10 Buffer solution, NWIS lot number, National Field Supply Service (NFSS) stock numbers Q122FLD, Q123FLD",
    "p99172": "pH 4 Buffer solution, NWIS lot number, National Field Supply Service (NFSS) stock numbers Q124FLD, Q125FLD",
    "p99173": "pH 7 Buffer solution, NWIS lot number, National Field Supply Service (NFSS) stock numbers Q126FLD, Q127FLD",
    "p99206": "NWIS lot number, capsule filter, 0.45 micron",
    "p99870": "Julian date, in-bottle digestion, ddd",
}

param_labels = [
    {"label": "Stream Width (ft)", "value": "p00004"},
    {"label": "Water temp (C)", "value": "p00010"},
    {"label": "Air temp (C)", "value": "p00020"},
    {"label": "Discharge (cfs)", "value": "p00061"},
    {"label": "Number of sample points", "value": "p00063"},
    {"label": "Specific conductance", "value": "p00095"},
    {"label": "Hydrogen ions, unfiltered (mg/L)", "value": "p00191"},
    {"label": "pH, unfiltered, field", "value": "p00400"},
    {"label": "pH, unfiltered, lab", "value": "p00403"},
    {"label": "CO2, unfiltered, (mg/L)", "value": "p00405"},
    {"label": "Organic Carbon, (mg/L)", "value": "p00681"},
    {"label": "Hardness, CaCO3, (mg/L)", "value": "p00900"},
    {"label": "Noncarbonate hardness, filtered, (mg/L)", "value": "p00905"},
    {"label": "Calcium, filtered, (mg/L)", "value": "p00915"},
    #     {'label':'', 'value':"p00925"},
    #     {'label':'', 'value':"p00930"},
    #     {'label':'', 'value':"p00931"},
    #     {'label':'', 'value':"p00932"},
    #     {'label':'', 'value':"p00935"},
    #     {'label':'', 'value':"p00940"},
    #     {'label':'', 'value':"p00945"},
    #     {'label':'', 'value':"p00950"},
    #     {'label':'', 'value':"p00955"},
    #     {'label':'', 'value':"p01000"},
    #     {'label':'', 'value':"p01002"},
    #     {'label':'', 'value':"p01025"},
    #     {'label':'', 'value':"p01027"},
    #     {'label':'', 'value':"p01040"},
    #     {'label':'', 'value':"p01042"},
    #     {'label':'', 'value':"p01045"},
    #     {'label':'', 'value':"p01046"},
    #     {'label':'', 'value':"p01049"},
    #     {'label':'', 'value':"p01051"},
    #     {'label':'', 'value':"p01055"},
    #     {'label':'', 'value':"p01056"},
    #     {'label':'', 'value':"p01090"},
    #     {'label':'', 'value':"p01092"},
    #     {'label':'', 'value':"p29801"},
    #     {'label':'', 'value':"p30209"},
    #     {'label':'', 'value':"p50015"},
    #     {'label':'', 'value':"p50280"},
    #     {'label':'', 'value':"p63676"},
    #     {'label':'', 'value':"p70301"},
    #     {'label':'', 'value':"p70302"},
    #     {'label':'', 'value':"p70303"},
    #     {'label':'', 'value':"p70331"},
    #     {'label':'', 'value':"p72219"},
    #     {'label':'', 'value':"p72220"},
    #     {'label':'', 'value':"p80154"},
    #     {'label':'', 'value':"p80155"},
    #     {'label':'', 'value':"p82398"},
    #     {'label':'', 'value':"p84164"},
    #     {'label':'', 'value':"p84171"},
    #     {'label':'', 'value':"p84182"},
    #     {'label':'', 'value':"p90095"},
    #     {'label':'', 'value':"p91157"},
    #     {'label':'', 'value':"p91165"},
    #     {'label':'', 'value':"p99105"},
    #     {'label':'', 'value':"p99111"},
    #     {'label':'', 'value':"p99156"},
    #     {'label':'', 'value':"p99159"},
    #     {'label':'', 'value':"p99161"},
    #     {'label':'', 'value':"p99163"},
    #     {'label':'', 'value':"p99164"},
    #     {'label':'', 'value':"p99171"},
    #     {'label':'', 'value':"p99172"},
    #     {'label':'', 'value':"p99173"},
    #     {'label':'', 'value':"p99206"},
    #     {'label':'', 'value':"p99870"},
]

# {
#     "p00004": "Stream width, feet",
#     "p00010": "Temperature, water, degrees Celsius",
#     "p00020": "Temperature, air, degrees Celsius",
#     "p00061": "Discharge, instantaneous, cubic feet per second",
#     "p00063": "Number of sampling points, count",
#     "p00095": "Specific conductance, water, unfiltered, microsiemens per centimeter at 25 degrees Celsius",
#     "p00191": "Hydrogen ion, water, unfiltered, calculated, milligrams per liter",
#     "p00400": "pH, water, unfiltered, field, standard units",
#     "p00403": "pH, water, unfiltered, laboratory, standard units",
#     "p00405": "Carbon dioxide, water, unfiltered, milligrams per liter",
#     "p00681": "Organic carbon, water, filtered, milligrams per liter",
#     "p00900": "Hardness, water, milligrams per liter as calcium carbonate",
#     "p00905": "Noncarbonate hardness, water, filtered, lab, milligrams per liter as calcium carbonate",
#     "p00915": "Calcium, water, filtered, milligrams per liter",
#     "p00925": "Magnesium, water, filtered, milligrams per liter",
#     "p00930": "Sodium, water, filtered, milligrams per liter",
#     "p00931": "Sodium adsorption ratio (SAR), water, number",
#     "p00932": "Sodium fraction of cations, water, percent in equivalents of major cations",
#     "p00935": "Potassium, water, filtered, milligrams per liter",
#     "p00940": "Chloride, water, filtered, milligrams per liter",
#     "p00945": "Sulfate, water, filtered, milligrams per liter",
#     "p00950": "Fluoride, water, filtered, milligrams per liter",
#     "p00955": "Silica, water, filtered, milligrams per liter as SiO2",
#     "p01000": "Arsenic, water, filtered, micrograms per liter",
#     "p01002": "Arsenic, water, unfiltered, micrograms per liter",
#     "p01025": "Cadmium, water, filtered, micrograms per liter",
#     "p01027": "Cadmium, water, unfiltered, micrograms per liter",
#     "p01040": "Copper, water, filtered, micrograms per liter",
#     "p01042": "Copper, water, unfiltered, recoverable, micrograms per liter",
#     "p01045": "Iron, water, unfiltered, recoverable, micrograms per liter",
#     "p01046": "Iron, water, filtered, micrograms per liter",
#     "p01049": "Lead, water, filtered, micrograms per liter",
#     "p01051": "Lead, water, unfiltered, recoverable, micrograms per liter",
#     "p01055": "Manganese, water, unfiltered, recoverable, micrograms per liter",
#     "p01056": "Manganese, water, filtered, micrograms per liter",
#     "p01090": "Zinc, water, filtered, micrograms per liter",
#     "p01092": "Zinc, water, unfiltered, recoverable, micrograms per liter",
#     "p29801": "Alkalinity, water, filtered, fixed endpoint (pH 4.5) titration, laboratory, milligrams per liter as calcium carbonate",
#     "p30209": "Discharge, instantaneous, cubic meters per second",
#     "p50015": "Transit rate, sampler, feet per second",
#     "p50280": "Site visit purpose, code",
#     "p63676": "Turbidity, water, unfiltered, broad band light source (400-680 nm), detectors at multiple angles including 90 +-30 degrees, ratiometric correction, NTRU",
#     "p70301": "Dissolved solids, water, filtered, sum of constituents, milligrams per liter",
#     "p70302": "Dissolved solids, water, short tons per day",
#     "p70303": "Dissolved solids, water, filtered, short tons per acre-foot",
#     "p70331": "Suspended sediment, sieve diameter, percent smaller than 0.0625 millimeters",
#     "p72219": "Sampler nozzle material, code",
#     "p72220": "Sampler nozzle diameter, code",
#     "p80154": "Suspended sediment concentration, milligrams per liter",
#     "p80155": "Suspended sediment discharge, short tons per day",
#     "p82398": "Sampling method, code",
#     "p84164": "Sampler type, code",
#     "p84171": "Sample splitter type, field, code",
#     "p84182": "Bottle or bag sampler material (construction), code",
#     "p90095": "Specific conductance, water, unfiltered, laboratory, microsiemens per centimeter at 25 degrees Celsius",
#     "p91157": "Suspended sediment, sediment mass recovered from whole water sample, dry weight, grams",
#     "p91165": "Suspended sediment, between 0.063 and 4 mm sieve diameter, sediment mass analyzed for particle size fractions, dry weight, grams",
#     "p99105": "Type of replicate, code",
#     "p99111": "Type of quality assurance data associated with sample, code",
#     "p99156": "Sulfuric acid NWIS lot number, 4.5 N (1:7), 1 mL, National Field Supply Service (NFSS) stock number Q438FLD",
#     "p99159": "Nitric acid NWIS lot number, 7.5-7.7 N, 2 mL, National Field Supply Service (NFSS) stock number Q436FLD",
#     "p99161": "Conductance standard NWIS lot number, 100 uS/cm KCl, National Field Supply Service (NFSS) stock number Q43FLD",
#     "p99163": "Conductance standard NWIS lot number, 500 uS/cm KCl, National Field Supply Service (NFSS) stock number Q45FLD",
#     "p99164": "Conductance standard NWIS lot number, 750 uS/cm KCl, National Field Supply Service (NFSS) stock number Q46FLD",
#     "p99171": "pH 10 Buffer solution, NWIS lot number, National Field Supply Service (NFSS) stock numbers Q122FLD, Q123FLD",
#     "p99172": "pH 4 Buffer solution, NWIS lot number, National Field Supply Service (NFSS) stock numbers Q124FLD, Q125FLD",
#     "p99173": "pH 7 Buffer solution, NWIS lot number, National Field Supply Service (NFSS) stock numbers Q126FLD, Q127FLD",
#     "p99206": "NWIS lot number, capsule filter, 0.45 micron",
#     "p99870": "Julian date, in-bottle digestion, ddd",
# }
