parameters = {
    "p00004": "Stream width, feet",
    "p00010": "Temperature, water, degrees Celsius",
    "p00020": "Temperature, air, degrees Celsius",
    "p00061": "Discharge, instantaneous, cubic feet per second",
    "p00063": "Number of sampling points, count",
    "p00095": "Specific conductance, water, unfiltered, microsiemens per centimeter at 25 degrees Celsius",
    "p00191": "Hydrogen ion, water, unfiltered, calculated, milligrams per liter",
    "p00400": "pH, water, unfiltered, field, standard units",
    "p00403": "pH, water, unfiltered, laboratory, standard units",
    "p00405": "Carbon dioxide, water, unfiltered, milligrams per liter",
    "p00681": "Organic carbon, water, filtered, milligrams per liter",
    "p00900": "Hardness, water, milligrams per liter as calcium carbonate",
    "p00905": "Noncarbonate hardness, water, filtered, lab, milligrams per liter as calcium carbonate",
    "p00915": "Calcium, water, filtered, milligrams per liter",
    "p00925": "Magnesium, water, filtered, milligrams per liter",
    "p00930": "Sodium, water, filtered, milligrams per liter",
    "p00931": "Sodium adsorption ratio (SAR), water, number",
    "p00932": "Sodium fraction of cations, water, percent in equivalents of major cations",
    "p00935": "Potassium, water, filtered, milligrams per liter",
    "p00940": "Chloride, water, filtered, milligrams per liter",
    "p00945": "Sulfate, water, filtered, milligrams per liter",
    "p00950": "Fluoride, water, filtered, milligrams per liter",
    "p00955": "Silica, water, filtered, milligrams per liter as SiO2",
    "p01000": "Arsenic, water, filtered, micrograms per liter",
    "p01002": "Arsenic, water, unfiltered, micrograms per liter",
    "p01025": "Cadmium, water, filtered, micrograms per liter",
    "p01027": "Cadmium, water, unfiltered, micrograms per liter",
    "p01040": "Copper, water, filtered, micrograms per liter",
    "p01042": "Copper, water, unfiltered, recoverable, micrograms per liter",
    "p01045": "Iron, water, unfiltered, recoverable, micrograms per liter",
    "p01046": "Iron, water, filtered, micrograms per liter",
    "p01049": "Lead, water, filtered, micrograms per liter",
    "p01051": "Lead, water, unfiltered, recoverable, micrograms per liter",
    "p01055": "Manganese, water, unfiltered, recoverable, micrograms per liter",
    "p01056": "Manganese, water, filtered, micrograms per liter",
    "p01090": "Zinc, water, filtered, micrograms per liter",
    "p01092": "Zinc, water, unfiltered, recoverable, micrograms per liter",
    "p29801": "Alkalinity, water, filtered, fixed endpoint (pH 4.5) titration, laboratory, milligrams per liter as calcium carbonate",
    "p30209": "Discharge, instantaneous, cubic meters per second",
    "p50015": "Transit rate, sampler, feet per second",
    "p50280": "Site visit purpose, code",
    "p63676": "Turbidity, water, unfiltered, broad band light source (400-680 nm), detectors at multiple angles including 90 +-30 degrees, ratiometric correction, NTRU",
    "p70301": "Dissolved solids, water, filtered, sum of constituents, milligrams per liter",
    "p70302": "Dissolved solids, water, short tons per day",
    "p70303": "Dissolved solids, water, filtered, short tons per acre-foot",
    "p70331": "Suspended sediment, sieve diameter, percent smaller than 0.0625 millimeters",
    "p72219": "Sampler nozzle material, code",
    "p72220": "Sampler nozzle diameter, code",
    "p80154": "Suspended sediment concentration, milligrams per liter",
    "p80155": "Suspended sediment discharge, short tons per day",
    "p82398": "Sampling method, code",
    "p84164": "Sampler type, code",
    "p84171": "Sample splitter type, field, code",
    "p84182": "Bottle or bag sampler material (construction), code",
    "p90095": "Specific conductance, water, unfiltered, laboratory, microsiemens per centimeter at 25 degrees Celsius",
    "p91157": "Suspended sediment, sediment mass recovered from whole water sample, dry weight, grams",
    "p91165": "Suspended sediment, between 0.063 and 4 mm sieve diameter, sediment mass analyzed for particle size fractions, dry weight, grams",
    "p99105": "Type of replicate, code",
    "p99111": "Type of quality assurance data associated with sample, code",
    "p99156": "Sulfuric acid NWIS lot number, 4.5 N (1:7), 1 mL, National Field Supply Service (NFSS) stock number Q438FLD",
    "p99159": "Nitric acid NWIS lot number, 7.5-7.7 N, 2 mL, National Field Supply Service (NFSS) stock number Q436FLD",
    "p99161": "Conductance standard NWIS lot number, 100 uS/cm KCl, National Field Supply Service (NFSS) stock number Q43FLD",
    "p99163": "Conductance standard NWIS lot number, 500 uS/cm KCl, National Field Supply Service (NFSS) stock number Q45FLD",
    "p99164": "Conductance standard NWIS lot number, 750 uS/cm KCl, National Field Supply Service (NFSS) stock number Q46FLD",
    "p99171": "pH 10 Buffer solution, NWIS lot number, National Field Supply Service (NFSS) stock numbers Q122FLD, Q123FLD",
    "p99172": "pH 4 Buffer solution, NWIS lot number, National Field Supply Service (NFSS) stock numbers Q124FLD, Q125FLD",
    "p99173": "pH 7 Buffer solution, NWIS lot number, National Field Supply Service (NFSS) stock numbers Q126FLD, Q127FLD",
    "p99206": "NWIS lot number, capsule filter, 0.45 micron",
    "p99870": "Julian date, in-bottle digestion, ddd",
}

param_labels = [
    {"label": "Stream width, feet", "value": "p00004"},
    {"label": "Temperature, water, degrees Celsius", "value": "p00010"},
    {"label": "Temperature, air, degrees Celsius", "value": "p00020"},
    {"label": "Discharge, instantaneous, cubic feet per second", "value": "p00061"},
    {"label": "Number of sampling points, count", "value": "p00063"},
    {"label": "Specific conductance, water, unfiltered, microsiemens per centimeter at 25 degrees Celsius", "value": "p00095"},
    {"label": "Hydrogen ion, water, unfiltered, calculated, milligrams per liter", "value": "p00191"},
    {"label": "pH, water, unfiltered, field, standard units", "value": "p00400"},
    {"label": "pH, water, unfiltered, laboratory, standard units", "value": "p00403"},
    {"label": "Carbon dioxide, water, unfiltered, milligrams per liter", "value": "p00405"},
    {"label": "Organic carbon, water, filtered, milligrams per liter", "value": "p00681"},
    {"label": "Hardness, water, milligrams per liter as calcium carbonate", "value": "p00900"},
    {"label": "Noncarbonate hardness, water, filtered, lab, milligrams per liter as calcium carbonate", "value": "p00905"},
    {"label": "Calcium, water, filtered, milligrams per liter", "value": "p00915"},
    {"label": "Magnesium, water, filtered, milligrams per liter", "value": "p00925"},
    {"label": "Sodium, water, filtered, milligrams per liter", "value": "p00930"},
    {"label": "Sodium adsorption ratio (SAR), water, number", "value": "p00931"},
    {"label": "Sodium fraction of cations, water, percent in equivalents of major cations", "value": "p00932"},
    {"label": "Potassium, water, filtered, milligrams per liter", "value": "p00935"},
    {"label": "Chloride, water, filtered, milligrams per liter", "value": "p00940"},
    {"label": "Sulfate, water, filtered, milligrams per liter", "value": "p00945"},
    {"label": "Fluoride, water, filtered, milligrams per liter", "value": "p00950"},
    {"label": "Silica, water, filtered, milligrams per liter as SiO2", "value": "p00955"},
    {"label": "Arsenic, water, filtered, micrograms per liter", "value": "p01000"},
    {"label": "Arsenic, water, unfiltered, micrograms per liter", "value": "p01002"},
    {"label": "Cadmium, water, filtered, micrograms per liter", "value": "p01025"},
    {"label": "Cadmium, water, unfiltered, micrograms per liter", "value": "p01027"},
    {"label": "Copper, water, filtered, micrograms per liter", "value": "p01040"},
    {"label": "Copper, water, unfiltered, recoverable, micrograms per liter", "value": "p01042"},
    {"label": "Iron, water, unfiltered, recoverable, micrograms per liter", "value": "p01045"},
    {"label": "Iron, water, filtered, micrograms per liter", "value": "p01046"},
    {"label": "Lead, water, filtered, micrograms per liter", "value": "p01049"},
    {"label": "Lead, water, unfiltered, recoverable, micrograms per liter", "value": "p01051"},
    {"label": "Manganese, water, unfiltered, recoverable, micrograms per liter", "value": "p01055"},
    {"label": "Manganese, water, filtered, micrograms per liter", "value": "p01056"},
    {"label": "Zinc, water, filtered, micrograms per liter", "value": "p01090"},
    {"label": "Zinc, water, unfiltered, recoverable, micrograms per liter", "value": "p01092"},
    {"label": "Alkalinity, water, filtered, fixed endpoint (pH 4.5) titration, laboratory, milligrams per liter as calcium carbonate", "value": "p29801"},
    {"label": "Discharge, instantaneous, cubic meters per second", "value": "p30209"},
    {"label": "Transit rate, sampler, feet per second", "value": "p50015"},
    {"label": "Site visit purpose, code", "value": "p50280"},
    {"label": "Turbidity, water, unfiltered, broad band light source (400-680 nm), detectors at multiple angles including 90 +-30 degrees, ratiom", "value": "p63676"},
    {"label": "Dissolved solids, water, filtered, sum of constituents, milligrams per liter", "value": "p70301"},
    {"label": "Dissolved solids, water, short tons per day", "value": "p70302"},
    {"label": "Dissolved solids, water, filtered, short tons per acre-foot", "value": "p70303"},
    {"label": "Suspended sediment, sieve diameter, percent smaller than 0.0625 millimeters", "value": "p70331"},
    {"label": "Sampler nozzle material, code", "value": "p72219"},
    {"label": "Sampler nozzle diameter, code", "value": "p72220"},
    {"label": "Suspended sediment concentration, milligrams per liter", "value": "p80154"},
    {"label": "Suspended sediment discharge, short tons per day", "value": "p80155"},
    {"label": "Sampling method, code", "value": "p82398"},
    {"label": "Sampler type, code", "value": "p84164"},
    {"label": "Sample splitter type, field, code", "value": "p84171"},
    {"label": "Bottle or bag sampler material (construction), code", "value": "p84182"},
    {"label": "Specific conductance, water, unfiltered, laboratory, microsiemens per centimeter at 25 degrees Celsius", "value": "p90095"},
    {"label": "Suspended sediment, sediment mass recovered from whole water sample, dry weight, grams", "value": "p91157"},
    {"label": "Suspended sediment, between 0.063 and 4 mm sieve diameter, sediment mass analyzed for particle size fractions, dry weight, grams", "value": "p91165"},
    {"label": "Type of replicate, code", "value": "p99105"},
    {"label": "Type of quality assurance data associated with sample, code", "value": "p99111"},
    {"label": "Sulfuric acid NWIS lot number, 4.5 N (1:7), 1 mL, National Field Supply Service (NFSS) stock number Q438FLD", "value": "p99156"},
    {"label": "Nitric acid NWIS lot number, 7.5-7.7 N, 2 mL, National Field Supply Service (NFSS) stock number Q436FLD", "value": "p99159"},
    {"label": "Conductance standard NWIS lot number, 100 uS/cm KCl, National Field Supply Service (NFSS) stock number Q43FLD", "value": "p99161"},
    {"label": "Conductance standard NWIS lot number, 500 uS/cm KCl, National Field Supply Service (NFSS) stock number Q45FLD", "value": "p99163"},
    {"label": "Conductance standard NWIS lot number, 750 uS/cm KCl, National Field Supply Service (NFSS) stock number Q46FLD", "value": "p99164"},
    {"label": "pH 10 Buffer solution, NWIS lot number, National Field Supply Service (NFSS) stock numbers Q122FLD, Q123FLD", "value": "p99171"},
    {"label": "pH 4 Buffer solution, NWIS lot number, National Field Supply Service (NFSS) stock numbers Q124FLD, Q125FLD", "value": "p99172"},
    {"label": "pH 7 Buffer solution, NWIS lot number, National Field Supply Service (NFSS) stock numbers Q126FLD, Q127FLD", "value": "p99173"},
    {"label": "NWIS lot number, capsule filter, 0.45 micron", "value": "p99206"},
    {"label": "Julian date, in-bottle digestion, ddd", "value": "p99870"},
]

# {
#     "p00004": "Stream width, feet",
#     "p00010": "Temperature, water, degrees Celsius",
#     "p00020": "Temperature, air, degrees Celsius",
#     "p00061": "Discharge, instantaneous, cubic feet per second",
#     "p00063": "Number of sampling points, count",
#     "p00095": "Specific conductance, water, unfiltered, microsiemens per centimeter at 25 degrees Celsius",
#     "p00191": "Hydrogen ion, water, unfiltered, calculated, milligrams per liter",
#     "p00400": "pH, water, unfiltered, field, standard units",
#     "p00403": "pH, water, unfiltered, laboratory, standard units",
#     "p00405": "Carbon dioxide, water, unfiltered, milligrams per liter",
#     "p00681": "Organic carbon, water, filtered, milligrams per liter",
#     "p00900": "Hardness, water, milligrams per liter as calcium carbonate",
#     "p00905": "Noncarbonate hardness, water, filtered, lab, milligrams per liter as calcium carbonate",
#     "p00915": "Calcium, water, filtered, milligrams per liter",
#     "p00925": "Magnesium, water, filtered, milligrams per liter",
#     "p00930": "Sodium, water, filtered, milligrams per liter",
#     "p00931": "Sodium adsorption ratio (SAR), water, number",
#     "p00932": "Sodium fraction of cations, water, percent in equivalents of major cations",
#     "p00935": "Potassium, water, filtered, milligrams per liter",
#     "p00940": "Chloride, water, filtered, milligrams per liter",
#     "p00945": "Sulfate, water, filtered, milligrams per liter",
#     "p00950": "Fluoride, water, filtered, milligrams per liter",
#     "p00955": "Silica, water, filtered, milligrams per liter as SiO2",
#     "p01000": "Arsenic, water, filtered, micrograms per liter",
#     "p01002": "Arsenic, water, unfiltered, micrograms per liter",
#     "p01025": "Cadmium, water, filtered, micrograms per liter",
#     "p01027": "Cadmium, water, unfiltered, micrograms per liter",
#     "p01040": "Copper, water, filtered, micrograms per liter",
#     "p01042": "Copper, water, unfiltered, recoverable, micrograms per liter",
#     "p01045": "Iron, water, unfiltered, recoverable, micrograms per liter",
#     "p01046": "Iron, water, filtered, micrograms per liter",
#     "p01049": "Lead, water, filtered, micrograms per liter",
#     "p01051": "Lead, water, unfiltered, recoverable, micrograms per liter",
#     "p01055": "Manganese, water, unfiltered, recoverable, micrograms per liter",
#     "p01056": "Manganese, water, filtered, micrograms per liter",
#     "p01090": "Zinc, water, filtered, micrograms per liter",
#     "p01092": "Zinc, water, unfiltered, recoverable, micrograms per liter",
#     "p29801": "Alkalinity, water, filtered, fixed endpoint (pH 4.5) titration, laboratory, milligrams per liter as calcium carbonate",
#     "p30209": "Discharge, instantaneous, cubic meters per second",
#     "p50015": "Transit rate, sampler, feet per second",
#     "p50280": "Site visit purpose, code",
#     "p63676": "Turbidity, water, unfiltered, broad band light source (400-680 nm), detectors at multiple angles including 90 +-30 degrees, ratiometric correction, NTRU",
#     "p70301": "Dissolved solids, water, filtered, sum of constituents, milligrams per liter",
#     "p70302": "Dissolved solids, water, short tons per day",
#     "p70303": "Dissolved solids, water, filtered, short tons per acre-foot",
#     "p70331": "Suspended sediment, sieve diameter, percent smaller than 0.0625 millimeters",
#     "p72219": "Sampler nozzle material, code",
#     "p72220": "Sampler nozzle diameter, code",
#     "p80154": "Suspended sediment concentration, milligrams per liter",
#     "p80155": "Suspended sediment discharge, short tons per day",
#     "p82398": "Sampling method, code",
#     "p84164": "Sampler type, code",
#     "p84171": "Sample splitter type, field, code",
#     "p84182": "Bottle or bag sampler material (construction), code",
#     "p90095": "Specific conductance, water, unfiltered, laboratory, microsiemens per centimeter at 25 degrees Celsius",
#     "p91157": "Suspended sediment, sediment mass recovered from whole water sample, dry weight, grams",
#     "p91165": "Suspended sediment, between 0.063 and 4 mm sieve diameter, sediment mass analyzed for particle size fractions, dry weight, grams",
#     "p99105": "Type of replicate, code",
#     "p99111": "Type of quality assurance data associated with sample, code",
#     "p99156": "Sulfuric acid NWIS lot number, 4.5 N (1:7), 1 mL, National Field Supply Service (NFSS) stock number Q438FLD",
#     "p99159": "Nitric acid NWIS lot number, 7.5-7.7 N, 2 mL, National Field Supply Service (NFSS) stock number Q436FLD",
#     "p99161": "Conductance standard NWIS lot number, 100 uS/cm KCl, National Field Supply Service (NFSS) stock number Q43FLD",
#     "p99163": "Conductance standard NWIS lot number, 500 uS/cm KCl, National Field Supply Service (NFSS) stock number Q45FLD",
#     "p99164": "Conductance standard NWIS lot number, 750 uS/cm KCl, National Field Supply Service (NFSS) stock number Q46FLD",
#     "p99171": "pH 10 Buffer solution, NWIS lot number, National Field Supply Service (NFSS) stock numbers Q122FLD, Q123FLD",
#     "p99172": "pH 4 Buffer solution, NWIS lot number, National Field Supply Service (NFSS) stock numbers Q124FLD, Q125FLD",
#     "p99173": "pH 7 Buffer solution, NWIS lot number, National Field Supply Service (NFSS) stock numbers Q126FLD, Q127FLD",
#     "p99206": "NWIS lot number, capsule filter, 0.45 micron",
#     "p99870": "Julian date, in-bottle digestion, ddd",
# }
